movierating/urls.py
from django.urls import path
from . import views

app_name='movierating'

urlpatterns=[
     path('home', views.home, name="home"),
     path('details/<int:id>', views.detail, name="detail"),
     path('login', views.login_view, name='login'),
     path('logout', views.logout_view, name='logout'),
     path('addmovie', views.add_movie,name='addmovie'),
     path('add-comment', views.add_comment, name='add-comment'),
     path('add-rating',views.add_rating,name='add-rating'),
     path('addrating', views.add_rate,name='addrating'),
      path("register", views.register_request, name="register")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movierating/', include('movierating.urls'))
]

movierating/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=300)
    director = models.CharField(max_length=300)
    cast = models.CharField(max_length=800)
    description = models.TextField(max_length=5000)
    release_date = models.DateField()
    averageRating = models.FloatField(default=0)
    image = models.URLField(default=None, null=True)
    videos = models.URLField(default=None, null=True)
    def __str__(self):
        return f'{self.name}'

class Message(models.Model):
    comment=models.CharField(max_length=600)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.comment

class Rating(models.Model):
    rating = models.IntegerField(null=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'movie')

        def __str__(self):
            return f'{self.rating}'

movierating/forms.py
from django import forms
from django.forms import ModelForm
from .models import Movie,Rating
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class Movieform(ModelForm):
    class Meta:
        model=Movie
        fields=('name', 'director', 'cast','description','release_date','averageRating','videos','image')

        widgets={
            'name':forms.TextInput({'class':'form-control','placeholder': 'Movie name'}),
            'director':forms.TextInput({'class':'form-control','placeholder': 'Director name'}),
            'cast':forms.TextInput({'class':'form-control','placeholder': 'the cast in the movie'}),
            'description':forms.Textarea({'class':'form-control','placeholder':'enter letters lessthan 5000'}),
            'averageRating':forms.TextInput({'class':'form-control','placeholder':'Rate a movie below 10'}),
            'videos':forms.TextInput({'class':'form-control','placeholder': 'please keep the link of youtube'}),
            'image':forms.TextInput({'class':'form-control','placeholder': 'please keep the link of image'}),
            'release_date':forms.TextInput({'class':'form-control','placeholder': 'the date in the format:YYY/MM/DD eg:2023-01-19'}),
        }

class Ratingform(ModelForm):
    class Meta:
        model=Rating
        fields=('rating','movie','user')

        widgets = {
            'rating':forms.TextInput({'class': 'form-control'}),
            'movie':forms.Select({'class': 'form-control'}),
            'user':forms.Select({'class': 'form-control'})
        }

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)
	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")
	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

movierating/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from .models import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import permission_required
from .forms  import Movieform,Ratingform,NewUserForm
from django.contrib import messages
# Create your views here.
def home(request):
    query = request.GET.get("title")
    allMovies = None
    if query:
        allMovies = Movie.objects.filter(name__icontains=query)
    else:
        allMovies = Movie.objects.all()  # select * from movie
    
    context = {
        "movies": allMovies,
    }

    return render(request, 'movierating/index.html', context)

def detail(request,id):
    movie = Movie.objects.get(pk = id)
    comment = Message.objects.filter(movie = movie)
    rating = Rating.objects.filter(user = request.user, movie = movie)
    if len(rating) == 0:
        rating = None
    context = {
        "movie": movie,
        "comments" : comment,
        "ratings" : rating
    }
    return render(request, 'movierating/details.html', context)

def login_view(request):
    if request.method == 'GET':
        return render(request, 'movierating/login.html')
    if request.method == 'POST':
        username = request.POST.get('username', "")
        password = request.POST.get('password', "")
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request,user)
            return redirect('movierating:home')
        else:
            return render(request, 'movierating/login.html', {'message': 'Invalid credentials, try again'})
def logout_view(request):
    logout(request)
    return redirect('movierating:login')

def add_movie(request):
    submitted=False
    if request.method == "POST":
        form = Movieform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('movierating:home')
    else:
        form = Movieform
    if 'submitted' in request.GET:
        submitted=True
    return render(request, 'movierating/addmovie.html', {'form':form})

def add_comment(request):
    if request.method == 'POST':
        comment = request.POST.get('comment')
        movie = Movie.objects.get(pk = request.POST.get('movie'))
        user = request.user
        new_comment = Message(comment = comment, user = user, movie = movie)

        new_comment.save()
        return redirect('movierating:detail', id = request.POST.get('movie'))


def add_rating(request):
    if request.method == 'POST':
        rating = int(request.POST.get('rating'))
        movie = Movie.objects.get(pk = request.POST.get('movie'))
        user = request.user
        new_rating, created = Rating.objects.get_or_create(user = user, movie = movie)
        new_rating.rating = rating
        new_rating.save()
        allratings = Rating.objects.filter(movie = movie)
        totalrating = sum([item.rating for item in allratings])
        avg_rating = totalrating / len(allratings)

        movie.averageRating = avg_rating
        movie.save()
        return redirect('movierating:detail', id = request.POST.get('movie'))



def resigter(request):
     return render(request, 'movierating/resigter.html',)

def add_rate(request):
    submitted=False
    if request.method == "POST":
        form = Ratingform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('movierating:home')
    else:
        form = Ratingform
    if 'submitted' in request.GET:
        submitted=True
    return render(request, 'movierating/addrating.html', {'form':form})



def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("movierating:login")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="movierating/register.html", context={"register_form":form})

movierating/templates/movierating/addmovie.html
{% extends 'movierating/base.html' %}
{% block content %}
<html>
    <head>
        <style>
        </style>
    </head>
<body>
    {% if submitted%}
    YOUR are submit
    {% else %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary">
    </form>
</body>
{% endif %}
{% endblock %}

movierating/templates/movierating/addrating.html
{% extends 'movierating/base.html' %}
{% block content %}
<html>
    <head>
        <style>
        </style>
    </head>
<body>
    {% if submitted%}
    YOUR are submit
    {% else %}
    <form action="" method="post">
        {% csrf_token %}
        <td>
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary">
    </form>
</body>
{% endif %}
{% endblock %}

movierating/templates/movierating/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <title>Moviereview</title>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
        <a class="navbar-brand" href="{% url 'movierating:home' %}">Movie Rating</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'movierating:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'movierating:addmovie'%}">Add Movies</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'movierating:addrating' %}">Rate here</a>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">My Profile</a>
      
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'movierating:login' %}">Logout</a>
              </div>
            </li>
            {% endif %}

          </ul>
          <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'movierating:home' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="title">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

    {% block content %}


    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

movierating/templates/movierating/details.html
{% extends 'movierating/base.html' %}

{% block content %}
<head>
    <style>
        .h5 {
            margin-left: 35%;
        }
    </style>
</head>
<div class="container">
    <br>
    <div class="card">
        <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <img src="{{ movie.image }}" alt="{{ movie.name }}" class="img-fluid">
            </div>
            <div class="col-md-8">
                <h3 class="text-center">
                    {{ movie.name }}
                </h3>
                <p>{{ movie.description }}</p>
                <h5>Director: {{ movie.director }}</h5>
                <h5>Cast: {{ movie.cast }}</h5>
                <h5>Rating: {{movie.averageRating}}/10</h5>
                <h5 style="color: blue ;" class="h5">Movie Trailer</h5>
                <iframe width="600" height="320" src="{{movie.videos}}">
                </iframe>

            </div>
        </div>
    </div>
    </div>
    <br>
    <br>
    <form action="{% url 'movierating:add-rating' %}" method="post">
        {% csrf_token %}
        <div class="input-group input-group-lg">
            <input type="text"  class="form-control" name="rating" placeholder="Rating here">
            <input type="hidden" value="{{movie.id}}" name="movie">
            </div>
            <br>
        <button type="submit" class="btn btn-secondary btn-lg">Rating here</button>
    </form>
    <br>
    <br>
    {% if ratings %}
        {% for rating in ratings %}
                <table>
                    <tbody><h4 style="color:rgb(255, 0, 225);"><i>name:{{rating.user}}</i></h4></tbody>
                    <tbody>
                    <h4 style="color: brown;"><b>rating:{{rating.rating}}</b></h4></tbody>
                </table>
                {% endfor %}{% endif %}
    <form action="{% url 'movierating:add-comment' %}" method="post">
        {% csrf_token %}
        <div class="input-group input-group-lg">
            <input type="text"  class="form-control" name="comment" placeholder="Comment here">
            <input type="hidden" value="{{movie.id}}" name="movie">
            </div>
            <br>
        <button type="submit" class="btn btn-secondary btn-lg">Comment</button>
    </form>
    <br>
    <br>
    {% for comment in comments %}
            <table>
                <tbody><h4 style="color:rgb(255, 0, 225);"><i>name:{{comment.user}}</i></h4></tbody>
                <tbody>
                <h4 style="color: brown;"><b>comment:{{comment.comment}}</b></h4></tbody>
            </table>
            {% endfor %}

{% endblock %}

movierating/templates/movierating/index.html
{% extends 'movierating/base.html' %}


{% block content %}


<div class="container">
    <br>
    <div class="card" id="backdrop">
        <div class="card-body">
            <div class="row">
                {% for movie in movies %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-center">
                            <img src="{{ movie.image }}" alt="" class="img-fluid" width="75%">
                            <h3 class="text-center">{{ movie.name }}</h3>
                            
                            <i class="text-center">{{ movie.release_date }}</i>
                            <a href="{% url 'movierating:detail' movie.pk %}">Read More</a>
                        </div>
                        
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


{% endblock %}

movierating/templates/movierating/login.html
<!DOCTYPE html>
<html>
    <head>
        <style>
            body{
                margin: 0;
                padding: 0;
                height: 100vh;
                font-family: sans-serif;
                background-image: url('https://images.pexels.com/photos/3945317/pexels-photo-3945317.jpeg');
                background-size: cover;
                background-repeat: no-repeat;
                background-position: center;
                overflow: hidden
            }@media screen and (max-width: 600px){
                body{
                    background-size: cover fixed;
                }
            }#particles-js{
                height: 100%
            }
            .loginBox{
                position: absolute;
                top: 50%;
                left: 60%;
                transform: translate(-50%,-50%);
                width: 350px;
                min-height: 200px;
                background: #000000;
                border-radius: 10px;
                padding: 40px;
                box-sizing: border-box
            }
            .user{
                margin: 0 auto;
                display: block;
                margin-bottom: 20px
            }
            h3{
                margin: 0;
                padding: 0 0 20px;
                color: #59238F;
                text-align: center
            }
            .loginBox input
            {
                width: 100%;
                margin-bottom: 20px
            }.loginBox input[type="text"], .loginBox input[type="password"]
            
            {
                border: none;border-bottom: 2px solid #262626;
                outline: none;
                height: 40px;
                color: #fff;
                background: transparent;
                font-size: 16px;
                padding-left: 20px;
                box-sizing: border-box
            }
            .loginBox input[type="text"]:hover,
             .loginBox input[type="password"]:hover{
                color: #42F3FA;
                border: 1px solid #42F3FA;
                box-shadow: 0 0 5px rgba(0,255,0,.3), 0 0 10px rgba(0,255,0,.2), 0 0 15px rgba(0,255,0,.1), 0 2px 0 black
            }
            .loginBox input[type="text"]:focus, .loginBox input[type="password"]:focus{border-bottom: 2px solid #42F3FA}.inputBox{position: relative}
            .inputBox span{
                position: absolute;top: 10px;color: #262626
            }.loginBox input[type="submit"]{border: none;
                outline: none;
                height: 40px;
                font-size: 16px;
                background: #59238F;
                color: #fff;
                border-radius: 20px;
                cursor: pointer
            }
            .loginBox a{
                color: #262626;
                font-size: 14px;
                font-weight: bold;
                text-decoration: none;
                text-align: center;
                display: block
            }
            a:hover{
                color: #00ffff
            }
            .h3{
                margin-top: 1%;
                margin-left: 23%;
                font-size: 500%;
                color: darkblue;
                font-weight: bold;
            }
            .p1{
                font-size: 250%;
                color:rgb(255, 0, 0);
                font-weight: bold;
                margin-left: 10%;
                margin-top: 10%;
            }
            .label1{
                color: white;
            }
        </style>
    </head>
    <body>
        {% if not user.is_authenticated %}
        <a href="{% url 'movierating:login' %}">Login here!</a>
        {% else %}
        <h3 class="h3">MovieRating</h3>
        {% endif %}
        <p class="p1">{{message}}</p>
<div class="loginBox"> <img class="user" src="https://i.ibb.co/yVGxFPR/2.png" height="100px" width="100px">
    <h3>Sign in here</h3>
    <form method="POST" action="{% url 'movierating:login' %}">
        {% csrf_token %}
        <div class="inputBox">
            <span class="input-group-addon"><i class="fa fa-user"></i></span>
    <label for="username" class="label1">Username</label>
        <input type="text" id="username" name="username" class="input1"><br/>
    <label for="password" class="label1">Password</label>
        <input type="password" id="password" name="password">
</div> 
<input type="submit" name="" value="Login">
    </form> 
    <a href="#">Forget Password<br> </a>
    <div class="text-center">
        <a href="{%url 'movierating:register' %}" style="color: #59238F;" id="reg">Register</a>
    </div>
    
</div>
</html>

movierating/templates/movierating/register.html
{% extends 'movierating/base.html' %}

{% block content %}         

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form}}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'movierating:login'%}">login</a> instead.</p>
</div>

{% endblock %}